ASP.NET Core Project/Models/CreatePersonViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_Core_Project.Models
{
    // Use to prevent overposting and to use data annotations to validate inputs when creating new person.
    public class CreatePersonViewModel
    {
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please enter a Name"), MaxLength(50), MinLength(2)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please enter a Phone number"), MaxLength(17), MinLength(8)]
        [Display(Name = "Phone")]
        public string Phone { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please enter a City"), MaxLength(50), MinLength(1)]
        [Display(Name = "City")]
        public string City { get; set; }
    }
}

ASP.NET Core Project/Controllers/PeopleEFController.cs
using ASP.NET_Core_Project.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_Core_Project.Controllers
{
    [Authorize]
    public class PeopleEFController : Controller
    {
        private readonly AppDbContext _context;
        public PeopleEFController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult ListOfPeopleEF()
        {
            List<PersonEFModel> ListOfPersons = _context.People.ToList();
            List<CityModel> ListOfCities = _context.City.ToList();
            List<LanguageModel> ListOfLanguages = _context.Language.ToList();
            List<PersonLanguageModel> ListOfPersonLanguages = _context.PersonLanguage.ToList();
            List<CountryModel> Countries = _context.Country.ToList();
            return View(ListOfPersons);
        }
        public IActionResult AddPerson()
        {
            ViewData["CityId"] = new SelectList(_context.City, "CityId", "City");
            ViewData["LanguageId"] = new SelectList(_context.Language, "LanguageId", "Language");
            return View();
        }
        [HttpPost]
        public IActionResult AddPerson(PersonEFModel person)
        {
            if (ModelState.IsValid)
            {
                _context.People.Add(person);
                _context.SaveChanges();
                return RedirectToAction("ListOfPeopleEF");
            }
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult DeletePerson(int id)
        {            
            _context.People.Remove(TargetPerson(id));
            _context.SaveChanges();
            return RedirectToAction("ListOfPeopleEF");
        }

        public IActionResult EditPerson(int id)
        {
            ViewData["CityId"] = new SelectList(_context.City, "CityId", "City");
            PersonEFModel targetPerson = TargetPerson(id);
            List<CityModel> ListOfCities = _context.City.ToList();
            return View(targetPerson);
        }
        [HttpPost]
        public IActionResult EditChoosenPerson(PersonEFModel person)
        {
            List<PersonEFModel> ListOfPersons = _context.People.ToList(); 
            foreach (PersonEFModel p in ListOfPersons)
            {
                if (p.PersonId == person.PersonId)
                {
                    p.Name = person.Name;
                    p.Phone = person.Phone;
                    p.CityId = person.CityId;
                }
            }
            _context.SaveChanges();
            return RedirectToAction("ListOfPeopleEF");
        }

        public PersonEFModel TargetPerson(int id)
        {
            List<PersonEFModel> ListOfPersons = _context.People.ToList();
            PersonEFModel targetPerson = new PersonEFModel();
            foreach (PersonEFModel p in ListOfPersons)
            {
                if (p.PersonId == id)
                {
                    targetPerson = p;
                }
            }
            return targetPerson;
        }
    }
}

ASP.NET Core Project/Views/PeopleEF/AddLanguage.cshtml
@model PersonLanguageModel
@{
    ViewData["Title"] = "AddLanguage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Add Language to Person</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddLanguage">
            <div class="form-group">
                <label class="control-label">Person:</label>
                <select asp-for="PersonId" class="form-control" asp-items="ViewBag.PersonId"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Language:</label>
                <select asp-for="LanguageId" class="form-control" asp-items="ViewBag.LanguageId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Person)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Language)
            </th>
        </tr>
    </thead>
    <tbody>
        </tbody>
    </table>
<div>
    <a asp-controller="PeopleEF" asp-action="ListOfPeopleEF">Back to List</a>
</div>

ASP.NET Core Project/Views/PeopleEF/AddPerson.cshtml
@model PersonEFModel

@{
    ViewData["Title"] = "Add Person";
}

<h1>Create Person</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddPerson">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">City:</label>
                <select asp-for="CityId" class="form-control" asp-items="ViewBag.CityId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ListOfPeopleEF">Back to People List</a>
</div>

ASP.NET Core Project/Views/PeopleEF/CreatePerson.cshtml
@model PersonEFModel

@{
    ViewData["Title"] = "Create Person";
}

<h1>Create Person</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePerson">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">City:</label>
                <select asp-for="CityId" class="form-control" asp-items="ViewBag.CityId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ListOfPeopleEF">Back to List</a>
</div>

ASP.NET Core Project/Views/PeopleEF/EditPerson.cshtml
@model PersonEFModel

@{
    ViewData["Title"] = "EditPerson";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit Person</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(model => model.Name)
            </td>
            <td>
                @Html.DisplayFor(model => model.Phone)
            </td>
            <td>
                @Html.DisplayFor(model => model.City.City)
            </td>
        </tr>
    </tbody>
</table>
<form asp-action="EditChoosenPerson" method="post" role="form">
    @Html.AntiForgeryToken()
    <h3>Edit Person:</h3>
    <input type="hidden" asp-for="PersonId" />
    <label asp-for="Name"></label>
    <input asp-for="Name" />
    <span asp-validation-for="Name"></span>
    <br>
    <label asp-for="Phone"></label>
    <input asp-for="Phone" />
    <span asp-validation-for="Phone"></span>
    <br>
    <br>
    <label class="control-label">City:</label>
    <select asp-for="CityId" class="form-control" asp-items="ViewBag.CityId" style="width:min-content"></select>
    <br>
    <input type="submit" class="btn btn-success" name="btnEditPerson" value="OK" />
</form>
<br>
<div>
    <a asp-controller="PeopleEF" asp-action="ListOfPeopleEF">Back to People List</a>
</div>

ASP.NET Core Project/Views/PeopleEF/ListOfPeopleEF.cshtml
@model IEnumerable<PersonEFModel>
@{
    ViewData["Title"] = "ListOfPeople";
}<div class="container">
    <h2>People Index</h2>
    <h3>List of people</h3>
    @if (User.IsInRole("Admin"))
    {
        <a asp-controller="Country" asp-action="ListOfCountries">List Countries</a>
        <br>
        <a asp-controller="City" asp-action="ListOfCities">List Cities</a>
        <br>
    }
    <a asp-controller="Language" asp-action="ListOfLanguages">List Languages</a>
    <br>
    <a asp-action="AddPerson">Add Person</a>
    <br>
    @if (User.IsInRole("Admin"))
    {
        <a asp-controller="Country" asp-action="AddCountry">Add Country</a>
        <br>
        <a asp-controller="City" asp-action="AddCity">Add City</a>
        <br>
        <a asp-controller="Language" asp-action="AddLanguage">Add Language</a>
        <br>
    }
    <a asp-controller="Language" asp-action="AddDeleteLanguagePerson">Add/Delete Language to/from Person</a>
    <br>
    <br>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Phone</th>
                <th>City</th>
                <th>Country</th>    
                <th>Languages</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var person in Model)
            {
            <tr>
                <td>@person.Name</td>
                <td>@person.Phone</td>
                <td>@person.City.City</td>
                <td>@person.City.Country.Country</td>
                <td>
                    @if (person.Languages != null)
                    {
                        @foreach (var l in person.Languages)
                        {
                            @Html.DisplayFor(modelItem => l.Language.Language)
                            <br>
                        }
                    }
                </td>
                <td>
                    @if (User.IsInRole("Admin"))
                    {
                        <a href="#" onclick="location.href = '@Url.Action("DeletePerson", "PeopleEF", new { id=person.PersonId })'">Delete</a>
                    }
                    <a href="#" onclick="location.href = '@Url.Action("EditPerson", "PeopleEF", new { id=person.PersonId })'">Edit</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>