ASP.NET Core Project/Controllers/AjaxController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP.NET_Core_Project.Models;
using Microsoft.AspNetCore.Authorization;

namespace ASP.NET_Core_Project.Controllers
{
    //[Authorize]
    public class AjaxController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetPersons()
        {
            PersonMemory personMemory = new PersonMemory();
            PeopleViewModel PeopleListViewModel = new PeopleViewModel() { PersonListView = personMemory.ReadPerson() };
            if (PeopleListViewModel.PersonListView.Count == 0 || PeopleListViewModel.PersonListView == null)
            {
                personMemory.SeedPersons();
            }
            List<PersonModel> personList = personMemory.ReadPerson();
            return PartialView("_PeopleListAjaxPartial", personList);
        }

        [HttpPost]
        public IActionResult FindPersonById(int personID)
        {
            PersonMemory personMemory = new PersonMemory();
            PersonModel personToFind = personMemory.ReadPerson(personID);
            List<PersonModel> personList = new List<PersonModel>();
            if (personToFind != null)
            {
                personList.Add(personToFind);
            }
            return PartialView("_PeopleListAjaxPartial", personList);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult DeletePersonById(int personID)
        {
            PersonMemory personMemory = new PersonMemory();
            PersonModel personToDelete = personMemory.ReadPerson(personID);
            bool success = false;
            if (personToDelete != null)
            {
                success = personMemory.DeletePerson(personToDelete);
            }
            if (success)
            {
                return StatusCode(200);
            }
            return StatusCode(404);
        }
    }
}

ASP.NET Core Project/Controllers/GameController.cs
using ASP.NET_Core_Project.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_Core_Project.Controllers
{
    public class GameController : Controller
    {
        public IActionResult NumberGuessing()
        {
            if (HttpContext.Session.GetInt32("RndNr") == null || HttpContext.Session.GetInt32("RndNr") == 0)
            {
                int rndNr = Utilities.RndNr();
                HttpContext.Session.SetInt32("RndNr", rndNr);
                ViewBag.Counter = "0";
            }
            return View();
        }
        [HttpPost]
        public IActionResult NumberGuessing(int guessedNr)
        {
            if (guessedNr != 0)
            {
                int rndNr = (int)HttpContext.Session.GetInt32("RndNr");
                string[] message = Utilities.CheckNumber(guessedNr, rndNr);
                if (message[2] == "EndGame")
                {
                    HttpContext.Session.SetInt32("RndNr", 0);
                    NumberGuessing();
                }
                ViewBag.Message = message[0];
                ViewBag.Counter = message[1];
            }
            else
            {
                ViewBag.Message = "You must enter a number 1-100. Please try again!";
            }
            return View();
        }
    }
}

ASP.NET Core Project/Controllers/ReactController.cs
using ASP.NET_Core_Project.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_Core_Project.Controllers
{
    public class ReactController : Controller
    {
        private readonly AppDbContext _context;
        public ReactController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult PersonList()
        {
            List<PersonEFModel> ListOfPersons = _context.People.ToList();
            return Json(ListOfPersons);
        }
        
        public JsonResult GetById(int id)
        {
            List<CountryModel> Countries = _context.Country.ToList();
            List<LanguageModel> ListOfLanguages = _context.Language.ToList();
            List<PersonEFModel> ListOfPersons = _context.People.Include(p => p.City).Include(p => p.Languages).ToList();
            var PersonInfo = ListOfPersons.Where(x => x.PersonId == id).SingleOrDefault();
            return Json(PersonInfo);
        }

        [HttpPost]
        public JsonResult AddEditPerson([FromBody]PersonDTO data)
        {
            List<CountryModel> ListOfCountries = _context.Country.ToList();
            List<LanguageModel> ListOfLanguages = _context.Language.ToList();
            List<CityModel> ListOfCities = _context.City.Include(p => p.Country).ToList();
            PersonEFModel personObj = new PersonEFModel();
            LanguageModel languageObj = new LanguageModel();
            CountryModel countryObj = new CountryModel();
            CityModel cityObj = new CityModel();
            PersonLanguageModel personLanguageObj = new PersonLanguageModel();
            bool b = true;

            personObj.Name = data.Name;
            personObj.Phone = data.Phone;
            cityObj.City = data.City;
            countryObj.Country = data.Country;
            try
            {
                if (data.PersonId == 0)
                {
                    //Add Person
                    for (int i = 0; i < ListOfCities.Count(); i++)
                    {
                        if (ListOfCities[i].City.ToLower() == data.City.ToLower())
                        {
                            for(int j = 0; j < ListOfCountries.Count(); j++)
                            {
                                if (ListOfCountries[j].Country.ToLower() == data.Country.ToLower() &&
                                    ListOfCountries[j].CountryId == ListOfCities[i].CountryId)
                                {
                                    personObj.CityId = ListOfCities[i].CityId;
                                    b = false;
                                    break;
                                }
                                else if (j == ListOfCountries.Count() - 1 && b)
                                {
                                    _context.Country.Add(countryObj);
                                    _context.SaveChanges();

                                    List<CountryModel> NewListOfCountries = _context.Country.ToList();
                                    countryObj = NewListOfCountries.LastOrDefault();
                                    cityObj.CountryId = countryObj.CountryId;

                                    _context.City.Add(cityObj);
                                    _context.SaveChanges();

                                    List<CityModel> NewListOfCities = _context.City.Include(p => p.Country).ToList();
                                    cityObj = NewListOfCities.LastOrDefault();
                                    personObj.CityId = cityObj.CityId;
                                    b = false;
                                }
                            }
                        }
                        else if(i == ListOfCities.Count() - 1 && b == true)
                        {
                            for(int j = 0; j < ListOfCountries.Count(); j++)
                            {
                                if (ListOfCountries[j].Country.ToLower() == data.Country.ToLower())
                                {
                                    cityObj.CountryId = ListOfCountries[j].CountryId;
                                    break;
                                }
                                else if (j == ListOfCountries.Count() - 1)
                                {
                                    _context.Country.Add(countryObj);
                                    _context.SaveChanges();

                                    List<CountryModel> NewListOfCountries = _context.Country.ToList();
                                    countryObj = NewListOfCountries.LastOrDefault();
                                    cityObj.CountryId = countryObj.CountryId;
                                }
                            }
                            _context.City.Add(cityObj);
                            _context.SaveChanges();

                            List<CityModel> NewListOfCities = _context.City.Include(p => p.Country).ToList();
                            cityObj = NewListOfCities.LastOrDefault();
                            personObj.CityId = cityObj.CityId;
                        }
                    }
                    _context.People.Add(personObj);
                    _context.SaveChanges();

                    List<PersonEFModel> NewListOfPersons = _context.People.ToList();
                    personObj = NewListOfPersons.LastOrDefault();
                    personLanguageObj.PersonId = personObj.PersonId;
                    for (int i = 0; i < ListOfLanguages.Count(); i++)
                    {
                        if (ListOfLanguages[i].Language.ToLower() == data.Language.ToLower())
                        {
                            personLanguageObj.LanguageId = ListOfLanguages[i].LanguageId;
                            break;
                        }
                        else if (i == ListOfLanguages.Count() - 1)
                        {
                            languageObj.Language = data.Language;
                            _context.Language.Add(languageObj);
                            _context.SaveChanges();

                            List<LanguageModel> NewListOfLanguages = _context.Language.ToList();
                            languageObj = NewListOfLanguages.LastOrDefault();
                            personLanguageObj.LanguageId = languageObj.LanguageId;
                        }
                    }
                    _context.PersonLanguage.Add(personLanguageObj);
                    _context.SaveChanges();
                }
                else
                {
                    //Edit Person
                    personObj.PersonId = data.PersonId;
                    for (int i = 0; i < ListOfCities.Count(); i++)
                    {
                        if (ListOfCities[i].City.ToLower() == data.City.ToLower())
                        {
                            for(int j = 0; j < ListOfCountries.Count(); j++)
                            {
                                if (ListOfCountries[j].Country.ToLower() == data.Country.ToLower() &&
                                    ListOfCountries[j].CountryId == ListOfCities[i].CountryId)
                                {
                                    personObj.CityId = ListOfCities[i].CityId;
                                    b = false;
                                    break;
                                }
                                else if (j == ListOfCountries.Count() - 1 && b)
                                {
                                    _context.Country.Add(countryObj);
                                    _context.SaveChanges();

                                    List<CountryModel> NewListOfCountries = _context.Country.ToList();
                                    countryObj = NewListOfCountries.LastOrDefault();
                                    cityObj.CountryId = countryObj.CountryId;

                                    _context.City.Add(cityObj);
                                    _context.SaveChanges();

                                    List<CityModel> NewListOfCities = _context.City.Include(p => p.Country).ToList();
                                    cityObj = NewListOfCities.LastOrDefault();
                                    personObj.CityId = cityObj.CityId;
                                    b = false;
                                }
                            }
                        }
                        else if(i == ListOfCities.Count() - 1 && b == true)
                        {
                            for(int j = 0; j < ListOfCountries.Count(); j++)
                            {
                                if (ListOfCountries[j].Country.ToLower() == data.Country.ToLower())
                                {
                                    cityObj.CountryId = ListOfCountries[j].CountryId;
                                    break;
                                }
                                else if (j == ListOfCountries.Count() - 1)
                                {
                                    _context.Country.Add(countryObj);
                                    _context.SaveChanges();

                                    List<CountryModel> NewListOfCountries = _context.Country.ToList();
                                    countryObj = NewListOfCountries.LastOrDefault();
                                    cityObj.CountryId = countryObj.CountryId;
                                }
                            }
                            _context.City.Add(cityObj);
                            _context.SaveChanges();

ASP.NET Core Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="js/PersonScript.js" defer></script>
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
    <title>@ViewBag.Title</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/16.13.0/umd/react.development.js" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.13.0/umd/react-dom.development.js" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/remarkable/1.7.1/remarkable.min.js" defer></script>
    <script src="@Url.Content("~/js/PersonReact.jsx")" defer></script>
</head>
<body>
    <header>
        <h1>Tomas homepage</h1>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP.NET_Core_Project</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Projects">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="FeverCheck">Fever Check</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="NumberGuessing">Number Guessing</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="ListOfPeople">List People</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ajax" asp-action="Index">List People with Ajax</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PeopleEF" asp-action="ListOfPeopleEF">List People EF</a>
                        </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="React" asp-action="Index">React</a>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="container">
            @RenderSection("scripts", required: false)
            @RenderBody()
        </div>
    </main>
    <footer>
        <br /><br />
              <p class="text-center">
                  &#9400;
                  @DateTime.Now.ToShortDateString() Tomas Varo
              </p>
    </footer>
</body>
</html>

ASP.NET Core Project/Views/Shared/_PeopleListAjaxPartial.cshtml
@model List<PersonModel>
<div class="container">
    <h3>List of people</h3>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Phone</th>
                <th>City</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var person in Model)
            {
                <tr>
                    <td>@person.PersonId</td>
                    <td>@person.Name</td>
                    <td>@person.Phone</td>
                    <td>@person.City</td>
                </tr>
            }
        </tbody>
    </table>
</div>

ASP.NET Core Project/Views/Shared/_PeopleListPartial.cshtml
@model PersonModel
<div class="row">
    @if (User.IsInRole("Admin"))
    {
        <div class="col-md-3">@Model.Name</div>
        <div class="col-md-3">@Model.Phone</div>
        <div class="col-md-3">@Model.City</div>

        <div class="col-md-3">
            <a href="#" onclick="location.href = '@Url.Action("DeletePerson", "People", new { id=Model.PersonId })'">Delete</a>

        </div>
    }
    @if (User.IsInRole("User"))
    {
        <div class="col-md-4">@Model.Name</div>
        <div class="col-md-4">@Model.Phone</div>
        <div class="col-md-4">@Model.City</div>
    }
</div>